### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by jcope2013** [ember-data/active-model-adapter#10]
i am not using babel as a dependency in my app but this seems to be babel related

```
Uncaught SyntaxError: Unexpected token {
```

https://github.com/ember-data/active-model-adapter/blob/master/addon/active-model-adapter.js#L10

Ember 1.13.2
Ember Data 1.13.4
Ember CLI 0.2.7

adding ember-cli-babel to my package.json fixs it

**Comment by fivetanley** [comment]
yeah you need to use babel.
