### ISSUE TITLE
Deprecation warnings with recent ember-data

### ISSUE THREAD

**Issue by DuBistKomisch** [ember-data/active-model-adapter#109]
Hey, I'm sure you're already aware of this (and it's maybe even already fixed... I see there's been a bunch of activity updating dependencies recently, looking forward to it landing, thanks!), but I just updated from ember-data 2.12 to 2.16 and now I'm getting deprecation warnings from `active-model-adapter`'s code when starting my application:

```
DEPRECATION: Ember.String.pluralize() is deprecated. Please explicitly: import { pluralize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
DEPRECATION: Ember.String.singularize() is deprecated. Please explicitly: import { singularize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
```

**Comment by pangratz** [comment]
Thanks for reporting!

**Comment by rmachielse** [comment]
This is happening since `ember-inflector@2.1.0`

**Comment by balinterdi** [comment]
Sorry, ignore my PR, I somehow didn't see that @rmachielse had already submitted one.
