### ISSUE TITLE
 Could not find module `active-model-adapter

### ISSUE THREAD

**Issue by jcope2013** [ember-data/active-model-adapter#11]
neither 

```

import ActiveModelAdapter from 'active-model-adapter';

```

or

```

import {ActiveModelSerializer} from 'active-model-adapter';

```

were working properly, i kept getting error

```
 Could not find module `active-model-adapter imported from `id/adapters/application`
```
Ember 1.13.2
Ember Data 1.13.4
Ember CLI 0.2.7

**Comment by fivetanley** [comment]
What version of the active model adapter?

**Comment by mswanson** [comment]
@fivetanley I am having the same issue. using 1.13.3 of active-model-adapter and 1.13.4 of ember data
