### ISSUE TITLE
Confusion RE: how to include

### ISSUE THREAD

**Issue by typeoneerror** [ember-data/active-model-adapter#22]
I added this as:

* first: in Brocfile... `app.import('bower_components/active-model-adapter/active-model-adapter.js')`
* second: added it as a direct link to a file in my index.html

In both cases, using the [usage](https://github.com/ember-data/active-model-adapter#usage) provided, I get

> Error while processing route: admin.index Could not find module `active-model-adapter` imported from `doki/adapters/application` Error: Could not find module `active-model-adapter` imported from `doki/adapters/application` 

Using 

    import DS from 'ember-data';
    export default DS.ActiveModelAdapter.extend()

instead of

    import ActiveModelAdapter from 'active-model-adapter';
    export default ActiveModelAdapter.extend()

The code works again and deprecation has gone away. Does this addon add ActiveModelAdapter back to the DS namespace? Is there a more thorough "usage" documentation?

**Comment by fivetanley** [comment]
You shouldn't have to use app.import if you run the following: https://github.com/ember-data/active-model-adapter#ember-cli

**Comment by typeoneerror** [comment]
Ah, silly me, I must've done the bower install. Thanks, @fivetanley, that did the trick!
