### ISSUE TITLE
Wrong git tag: 1.13.13

### ISSUE THREAD

**Issue by tricknotes** [ember-data/active-model-adapter#25]
1.13.3 seems tagged as [1.13.13](https://github.com/ember-data/active-model-adapter/tree/1.13.13).

**Comment by bmac** [comment]
Good catch. Would it be safe to delete the `1.13.13` tag?

**Comment by bmac** [comment]
I've created a new tag for [1.13.3](https://github.com/ember-data/active-model-adapter/releases/tag/1.13.3)

**Comment by tricknotes** [comment]
Thanks @bmac .

I'm not sure that deleting `1.13.13` tag is safety.
But it may make new comer confusing.

**Comment by bmac** [comment]
I have deleted the tag `1.13.13`. If anyone finds an issue with it missing we can always add it back.
