### ISSUE TITLE
npm install: shasum check fails for v1.13.4

### ISSUE THREAD

**Issue by DenizOkcu** [ember-data/active-model-adapter#28]
Hi all,

I got this error message while installing version 1.13.4.
Version 1.13.3 is fine.

```
npm ERR! Darwin 14.4.0
npm ERR! argv "/Users/deniz/.nvm/versions/node/v0.12.7/bin/node" "/Users/deniz/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! shasum check failed for /var/folders/wz/_d0wflt540j52g8_vd94qbs40000gn/T/npm-2362-f6536181/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
npm ERR! Expected: 894bbae414278da6f68229959ee72aff34a669b5
npm ERR! Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
npm ERR! From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
```

Do you need any further information?
Cheers, Deniz

**Comment by fivetanley** [comment]
can you try:

`npm cache clean && rm -rf node_modules && npm i`

Also what version of npm are you using?

**Comment by jcope2013** [comment]
i fixed it by changing registry

```
npm config set registry https://registry.npmjs.org/
```

**Comment by fivetanley** [comment]
@jcope2013 Weird, you shouldn't have had to change your registry. What was your registry before?

**Comment by jcope2013** [comment]
@fivetanley i was having issues at one point recently so i changed it to http://registry.npmjs.org/ but now i am back to https

**Comment by DenizOkcu** [comment]
@fivetanley thanks for the quick answer. I tried everything like rm node_modules and npm cache clean.
my node version is: 0.12.7 (installed via nvm)
my npm version is: 2.11.13

seems to be the wrong shasum for the version 1.13.4 file in the npm registry.
Dont know if things work that way :-)
The problem only occurs with the most recent version.

**Comment by fivetanley** [comment]
Weird, I can install it just fine. There is no npm version 2.11.13, but there is 2.11.3 and I tried it with that. I'm not sure how it could be wrong in the registry.

What's the output of `npm config get registry` ?

**Comment by jcope2013** [comment]
@fivetanley on another machine, i had no problems, the output is

```
npm config get registry
https://registry.npmjs.org/
```

it seems if you have the http not https registry you get above error

**Comment by DenizOkcu** [comment]
Yes v2.11.3 it is. 
I will check everything again at work tomorrow and post my findings.

We had the same problem from different machines and even from our CI (different network). changing the value from `"^1.13.3"` to `"1.13.3"` in the package.json fixes it for the moment (completly acceptable for me right now). Thanks again.

**Comment by jcope2013** [comment]
@DenizOkcu what is the output of ```npm config get registry```?

**Comment by DenizOkcu** [comment]
@jcope2013 it returns ``` https://registry.npmjs.org/ ```

@fivetanley I really have no idea how the npm registry works internally. This is what I did:
1. opened: https://registry.npmjs.org/active-model-adapter/1.13.4
2. looked for shasum -> ``` shasum: "894bbae414278da6f68229959ee72aff34a669b5" ```
3. downloaded the file: ```wget https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz ```
4. and run check for the shasum: ```shasum active-model-adapter-1.13.4.tgz``` got ```23212ae5107f7b7b1c109f72a69cc554eb3b491e  active-model-adapter-1.13.4.tgz```

npm install log says:
```
1328 error shasum check failed for /var/folders/wz/_d0wflt540j52g8_vd94qbs40000gn/T/npm-27553-5bf606c6/registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
1328 error Expected: 894bbae414278da6f68229959ee72aff34a669b5
1328 error Actual:   23212ae5107f7b7b1c109f72a69cc554eb3b491e
1328 error From:     https://registry.npmjs.org/active-model-adapter/-/active-model-adapter-1.13.4.tgz
```
For v1.13.3 the shasum from the registry and from the local file match.
I hope this helps in some way.

**Comment by fivetanley** [comment]
@DenizOkcu I opened a new issue.  As I can't reproduce I'm not sure what to do. I'm hoping the npm team can help us figure out what went wrong.

**Comment by michaeldupuisjr** [comment]
I was seeing the same problem as @DenizOkcu while on npm `2.7.x`. Updating to `2.13.1` allowed me to  `npm install` without issue.

**Comment by DenizOkcu** [comment]
@fivetanley thank you for caring about this! Lets see what the npm guys say. I am curious about it.

**Comment by vala** [comment]
As @DenizOkcu 1.13.3 works. In my case, with ember-cli I could install it this way : `ember install active-model-adapter@1.13.3`

**Comment by vala** [comment]
@Patsy-issa As mentionned here : http://stackoverflow.com/a/20648825/685925 you should never bypass the sha-checksum system, since the file can be corrupted and you would expose yourself to a security risk. Now, that's still up to you heh !

**Comment by Patsy-issa** [comment]
@vala Should have led my comment with a warning, I understand the repercussions but I am the only one out of 3 devs to have this problem, the rest were able to nombom and get it running, hopefully there will be an official fix for this soon.

**Comment by jcope2013** [comment]
would publishing a new release clear up this issue even though there are no changes? another dev on my team hit it also

**Comment by fivetanley** [comment]
1.13.5 is out. Please try it out and let me know if this is resolved.

**Comment by fivetanley** [comment]
I guess i have to publish manually for npm, hold on.

**Comment by fivetanley** [comment]
Alright sorry everyone, it looks like our automation busted with Travis CI :\ I'll have to look into it. 1.13.5 is out for real.

**Comment by DenizOkcu** [comment]
@five 1.13.5 works perfect. Thank you!
