### ISSUE TITLE
extract support?

### ISSUE THREAD

**Issue by abFx** [ember-data/active-model-adapter#31]
Is the extract method still available, can't find here in the repo or is there a new alternative in Ember data

**Comment by fivetanley** [comment]
cc @wecc

**Comment by wecc** [comment]
`extract` is a part of the old Serializer API and is inherited from the `JSONSerializer`. It's new counterpart would be the `normalizeResponse` method and just as you previously had `extractArray` and `extractSingle` you can now use `normalizeArrayResponse` and `normalizeSingleResponse`.

**Comment by fivetanley** [comment]
Closing as I think wecc answered it.
