### ISSUE TITLE
extractPolymorphicRelationships doesn't handle null relationships

### ISSUE THREAD

**Issue by ryanjm** [ember-data/active-model-adapter#37]
Sometimes a relationship isn't set and the extraction doesn't properly account for that so it throws an error:

```
unknown problem undefined TypeError: Cannot read property 'id' of null
```

The code that is dealing with this issue:

```
function extractPolymorphicRelationships(key, relationshipMeta, resourceHash, relationshipKey) {
  var polymorphicKey = decamelize(key);
  if (polymorphicKey in resourceHash && typeof resourceHash[polymorphicKey] === 'object') {
    if (relationshipMeta.kind === 'belongsTo') {
      var hash = resourceHash[polymorphicKey];
      var id = hash.id;
      var type = hash.type;

      resourceHash[relationshipKey] = { id: id, type: type };
      // otherwise hasMany
    } 
    // ...
```

In this case `hash` ends up being `null` and then `hash.id` fails.

The part I don't understand is that this doesn't match was is currently on [master](https://github.com/ember-data/active-model-adapter/blob/858d7b678ca22e4c99f5c0b8d2d91ea8a73532a8/addon/active-model-serializer.js#L340).

**Comment by fivetanley** [comment]
What's in master isn't always the most released version. That being said, I'm pushing out a new release right now. We fixed this bug in https://github.com/ember-data/active-model-adapter/pull/35.

**Comment by fivetanley** [comment]
This is in 1.13.6!

**Comment by ryanjm** [comment]
I'm using Ember Data 1.13.9 and still running into this issue. How can I check to make sure Ember Data us using 1.13.6 of Active Model Adapter?

**Comment by jcope2013** [comment]
@ryanjm make sure ``` "active-model-adapter": "1.13.6" ``` is in your package.json

**Comment by ryanjm** [comment]
@jcope2013 - Thank you!! That worked great.
