### ISSUE TITLE
[Question] What is the purpose of the addon?

### ISSUE THREAD

**Issue by WooDzu** [ember-data/active-model-adapter#39]
I'm struggling to understand the purpose of this addon.

Is it supposed to polyfill ActiveModel Adapter and Serializer in ember-data 2.0?
I have a number of huge C++ API's (Rails style payloads) and moving them to JSON API style is currently out of scope so was hoping I could use the addon with ember 2.0 and carry on the old way.

If this is not the case is there any easy way or migration path to convert the Rails-style payload to JSON-API?

**Comment by fivetanley** [comment]
It's not really a polyfill, we just moved the code out of Ember Data itself into this addon. We'll release a 2.0 of this addon soon, although to my knowledge it shouldn't be too far behind Ember Data 2.0

**Comment by WooDzu** [comment]
@fivetanley I take your replay as 'wait for 2.0 and keep using rails-style paylods' please correct me if I'm wrong.
Is there any ETA for 2.0, anything I can help evolve or test?
