### ISSUE TITLE
2.0.0 release does not work

### ISSUE THREAD

**Issue by indirect** [ember-data/active-model-adapter#47]
```
$ ember install active-model-adapter
$ ember generate adapter application
```

Copy and paste from readme into `app/adapters/application.js`:

```
import ActiveModelAdapter from 'active-model-adapter';

export default ActiveModelAdapter.extend();
```

Boot the app with `ember s`, load the page, and get this exception:

```
Error while processing route: index Could not find module `active-model-adapter` imported from `push-perf/adapters/application` Error: Could not find module `active-model-adapter` imported from `push-perf/adapters/application`
    at requireFrom (http://localhost:4200/assets/vendor.js:119:13)
    at reify (http://localhost:4200/assets/vendor.js:106:22)
    at mod.state (http://localhost:4200/assets/vendor.js:149:17)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at _extractDefaultExport (http://localhost:4200/assets/vendor.js:78736:20)
    at resolveOther (http://localhost:4200/assets/vendor.js:78471:32)
    at superWrapper (http://localhost:4200/assets/vendor.js:31688:20)
    at exports.default._emberRuntimeSystemObject.default.extend.resolve (http://localhost:4200/assets/vendor.js:15368:35)
    at Object.resolve [as resolver] (http://localhost:4200/assets/vendor.js:15102:23)
```

**Comment by indirect** [comment]
If I manually `npm install active-model-adapter@1.13.6`, everything works just fine. This is a bug in 2.0.0.

**Comment by fivetanley** [comment]
Can you try 2.0.1? This seems to be happening occasionally and publishing a new version on npm fixes it. Wish I had a way to track it down.

**Comment by indirect** [comment]
FWIW, I had the exact same issue while using a script tag from github in ember-twiddle, so it's not an NPM issue.

**Comment by fivetanley** [comment]
Do you have a link to the twiddle? That'd be great too.

**Comment by indirect** [comment]
Sure, here it is broken while pulling in master: http://ember-twiddle.com/3fffd991af835a9a8422

**Comment by indirect** [comment]
Huh, I can confirm that it does work with 2.0.1 via `npm install active-model-adapter@2.0.1`. So I'm not sure what's up with the twiddle from master. :)

**Comment by fivetanley** [comment]
So there's a couple things there. The stuff in the dist repository is for globals mode users. While we do output modules that could be used by Ember twiddle, they're wrapped in their own anonymous function and have a copy of the loader.js registry. This means that when `import ActiveModelAdapter from 'active-model-adapter'` gets compiled down to AMD modules, it does get loaded into a registry but not the app's registry on ember twiddle.

After tracking that down, I can't get it to build on twiddle yet. I'll have to ask @rwjblue and @stefanpenner if they have any ideas here. Maybe we're doing something wrong in our addon.

**Comment by fivetanley** [comment]
Also a tip for making JS demos is that Github will block loading them from script tags, so you have to use something like http://rawgit.com/ to make them work on JSBin, Ember Twiddle, etc.

**Comment by fivetanley** [comment]
Ah cool. I have no idea why it's suddenly working now. Are we able to close this issue then?

**Comment by indirect** [comment]
Okay, thanks! I initially thought the problem was just using it in the twiddle, but then I got the same error using NPM. :)

Now that it's working locally we can close this! Should I open a new issue for a build that can be used in a twiddle?

**Comment by fivetanley** [comment]
I'm not sure what format they expect or what I can use. I'll open an issue since my build breaks anyway.

**Comment by fivetanley** [comment]
Ah, figured it out. Opening a new issue.

**Comment by simo163** [comment]
v2.0.1 worked to me with ember 2.0

**Comment by jpaas** [comment]
I'm cannot get past this problem of the module not being found. I've tried a number of combinations of 2.x ember and ember-data releases together with active-model-adapter 2.0.1. Deleting node_modules and bower_components and cache clean between each change. Does anybody have any other suggestions or a specific config I can try?

**Comment by plicjo** [comment]
In version 2.0.3, the active-model-adapter only worked when I installed it via npm: `ember install:npm active-model-adapter`.

Install it via bower (`ember install:bower active-model-adapter`) didn't work. I got a `Could not find module `active-model-adapter`` too,
