### ISSUE TITLE
Bug: Missing relationships after updating

### ISSUE THREAD

**Issue by WooDzu** [ember-data/active-model-adapter#54]
Another issues I came across after updating to 2.x and active-model-adapter.

My models have this example keys:
```js
project: DS.belongsTo('project'),
folders: DS.hasMany('folder'),
asset: DS.belongsTo('asset'), // declared embedded in serializer
```
upon updating, both `project` and `folders` relations become empty as opposed to `asset` declared as `embedded`. It turned out that actve-model-serializer appends _id and _ids to the keys it expects in payload eg (project_id and folder_ids) which was not the case before updating. To workaround this, in my main application serializer I declared:

```js
    keyForRelationship(relationModelName) {
        return relationModelName;
    },
```

**Comment by aaronrenner** [comment]
I ran into this issue too. I was able to work around this by deleting the `config.default_key_type = :name` line from my active_model_serializer initializer in my rails app:

```ruby
ActiveModel::Serializer.setup do |config|
  # Delete the following line
  # config.default_key_type = :name
end
```

**Comment by fivetanley** [comment]
What is the current naming convention in the current version of ActiveModelSerializers?

**Comment by fivetanley** [comment]
I'm happy to support this I just don't know which order we should prefer to look things up in.
