### ISSUE TITLE
ID is not stored

### ISSUE THREAD

**Issue by mxrguspxrt** [ember-data/active-model-adapter#55]
When from REST comes response for belongsTo or hasMany with prefix _id or _ids, then this value is not stored on the model.

That creates weird situation where I can not make comparisons between ID-s without loading assocation (and resolving a promise). 

This is not optimal and makes my code longer.

**Comment by fivetanley** [comment]
Do you have some sample code or a JSbin?

**Comment by mxrguspxrt** [comment]
Imagine that you have comment with belongsTo('post', { async: true }), now your response is { comment: { post_id: 1 } }.

Now there is now way to access only this ID. You must call comment.get('post.id'), but that means full post is asked from server and id is returned.

**Comment by pangratz** [comment]
This is addressed by https://github.com/emberjs/rfcs/pull/57, which is handled in PR https://github.com/emberjs/data/pull/3303 (not merged yet).

Once this is in ember-data, you can get the id via: `comment.belongsTo('post').id()`...

**Comment by mxrguspxrt** [comment]
Cool, thanks.
