### ISSUE TITLE
Using `ApplicationInstance.registry.register` is deprecated since Ember 2.1

### ISSUE THREAD

**Issue by maartenparmentier** [ember-data/active-model-adapter#70]
I'm getting a depecration warning on latest Ember on these lines

```
registry.register('adapter:-active-model', _activeModelAdapter['default']);
registry.register('serializer:-active-model', _activeModelAdapterActiveModelSerializer['default']);
```

http://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry

**Comment by kenips** [comment]
instance initializer is only removed in 2.0.3. What version are you using?

**Comment by trianglegrrl** [comment]
Same here on E/ED 2.2.x.

**Comment by vasilakisfil** [comment]
same here

**Comment by fivetanley** [comment]
For people +1'ing can you please tell us what version of ActiveModelAdapter and Ember Data you are using?

**Comment by vasilakisfil** [comment]
I used Ember 2.1, ember-data 2.1 and ActiveModelAdapter 2.0.1. Same on Ember 2.2 and ember-data 2.2.

**Comment by maartenparmentier** [comment]
"active-model-adapter": "2.0.1"

and E/ED: 2.2

**Comment by fivetanley** [comment]
Can you try ActiveModelAdapter 2.0.3?

**Comment by maartenparmentier** [comment]
Jip, that worked for me! Thx
