### ISSUE TITLE
Broken using ember data ember-data 2.3.0-beta.2 and ember-cli 2.2.0-beta.1 and active-model-adapter 2.0.3

### ISSUE THREAD

**Issue by jcope2013** [ember-data/active-model-adapter#72]
something in the ember-cli 2.2.0-beta.1 release seems to have broken it, can confirm it works with ember-cli 1.13.13

the import of DS gets messed up which causes InvalidError, errorsHashToArray and RESTAdapter to all be undefined https://github.com/ember-data/active-model-adapter/blob/master/addon/active-model-adapter.js

just clone, install dependencies and try to ember serve and you will see error

https://github.com/jcope2013/active-model-adapter-ember-cli-2-beta-issue

**Comment by bmac** [comment]
Thanks for the great bug report @jcope2013. My initial investigation suggests this is a bug in ember-data 2.3.0-beta.2 and not the active-model-adapter.

**Comment by jcope2013** [comment]
forgot to add that they work fine when using ember-cli 1.13.13 but the 2.0 beta version breaks it

**Comment by bmac** [comment]
Thanks @jcope2013. You are correct seems to be an issue with the Ember CLI 2.2 beta.

**Comment by bmac** [comment]
Thanks again for reporting the issue @jcope2013. @rwjblue managed to track down this issue to a problem with how ember-cli-shims was interacting with the newly addonized Ember Data https://github.com/emberjs/data/pull/3995. 

I've released @rwjblue's pr as https://github.com/emberjs/data/releases/tag/v2.3.0-beta.3. Ember Data will now takes over the old `ember-cli-shims`'s responsibility and prompts you to update to `0.1.0` of `ember-cli-shims`.

**Comment by jcope2013** [comment]
yeah can confirm it works thanks

**Comment by rwjblue** [comment]
Awesome!
