### ISSUE TITLE
`accepts_nested_attributes_for` with active-model-adapter

### ISSUE THREAD

**Issue by GCorbel** [ember-data/active-model-adapter#74]
Hi,

When I save a record with association, I have this kind of params in my Rails app : `{"course_id"=>"1", "user"=>{"email"=>"rst", "contacts"=>[{"fullname"=>"rst", "phone"=>"rst", "email"=>"rst"}]}}` which is corrected.

When I do something like `Subscription.new params`, it gives `ActiveRecord::AssociationTypeMismatch: User(#70224777299060) expected, got Hash(#70224747397500)`. Which is correct too but it can be useful to have an option to have this json `{"course_id"=>"1", "user_attributes"=>{"email"=>"rst", "contacts_attributes"=>[{"fullname"=>"rst", "phone"=>"rst", "email"=>"rst"}]}}` in order to use it with `accepts_nested_attributes_for`.

What you think ? I'm ready to contribute if you want.

**Comment by GCorbel** [comment]
It seems to work as I want with this serializer : 

    import { ActiveModelSerializer } from 'active-model-adapter';

    export default ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
      attrs: {
        user: { embedded: 'always' },
        contacts: { embedded: 'always' },
      },
      _serializeEmbeddedBelongsTo: function (snapshot, json, relationship) {
        var embeddedSnapshot = snapshot.belongsTo(relationship.key);
        var serializedKey = this.keyForAttribute(relationship.key, 'serialize') + '_attributes';
        if (!embeddedSnapshot) {
          json[serializedKey] = null;
        } else {
          json[serializedKey] = embeddedSnapshot.record.serialize({ includeId: true });
          this.removeEmbeddedForeignKey(snapshot, embeddedSnapshot, relationship, json[serializedKey]);

          if (relationship.options.polymorphic) {
            this.serializePolymorphicType(snapshot, json, relationship);
          }
        }
      },
      _serializeEmbeddedHasMany: function (snapshot, json, relationship) {
        var serializedKey = this.keyForAttribute(relationship.key, 'serialize') + '_attributes';

        Ember.warn('The embedded relationship \'' + serializedKey + '\' is undefined for \'' + snapshot.modelName + '\' with id \'' + snapshot.id + '\'. Please include it in your original payload.', Ember.typeOf(snapshot.hasMany(relationship.key)) !== 'undefined', { id: 'ds.serializer.embedded-relationship-undefined' });

        json[serializedKey] = this._generateSerializedHasMany(snapshot, relationship);
      }
    });

It's uggly. For a clean solution, I think we have contribute to ember data to change those functions in `DS.EmbeddedRecordsMixin`.

I still don't know if it's a good idea or if there is a better way. What you think?

**Comment by bmac** [comment]
Its strange that `_serializeEmbeddedBelongsTo` uses `keyForAttribute` and not `keyForRelationship`. Any idea why it does that @wecc or @fivetanley? 

@GCorbel If Ember Data was changed to use `keyForRelationship` would overriding that method to return the key + `_attributes` solve your problem?

**Comment by fivetanley** [comment]
probably scumbag stanley didn't think through the code all the way. keyForRelationship seems more correct.

**Comment by GCorbel** [comment]
@bmac, yes, I think it will solve my problem. Thanks!

**Comment by bmac** [comment]
Great @GCorbel. If you are still interested in contributing changing `_serializeEmbeddedHasMany` and `_serializeEmbeddedBelongsTo` to use `keyForRelationship` in https://github.com/emberjs/data/blob/master/addon/-private/serializers/embedded-records-mixin.js would be a great fix.

**Comment by GCorbel** [comment]
@bmac it makes sense. I'll try to do it tonight.

**Comment by GCorbel** [comment]
Done!

**Comment by mmahalwy** [comment]
Hey, forgive my ignorance, how can I make this work with `accepts_nested_attributes_for` ? Just copy-pasta the code snippet above?
