### ISSUE TITLE
Could not find module `ember-data` imported from `active-model-adapter/active-model-adapter`

### ISSUE THREAD

**Issue by tachun** [ember-data/active-model-adapter#75]
Im using ember-cli 2.2.0-beta.2 with active-model-adapter, but I got this error:
```
Uncaught Error: Could not find module `ember-data` imported from `active-model-adapter/active-model-adapter`
```
I've removed node_modules and bower_components and caches then reinstall again, also `ember install active-model-adapter` again, but still get same error, Is anyone has same issue?

using:
ActiveModelAdapter: 2.0.3
ember Data: 2.2.1
ember: 2.2.0
ember-cli: 2.2.0-beta.2
ember-cli-shims: 0.1.0
loader.js: 3.5.0

Thanks

**Comment by pangratz** [comment]
If I am not mistaken, `ember-cli-shims` `v0.1.0` requires `ember-data` `v2.3.0-beta` ...

**Comment by fivetanley** [comment]
@pangratz is correct. Please feel free to reopen if you are still having issues after switching ember-cli-shims to 0.1.0
