### ISSUE TITLE
Uncaught TypeError: app[initializerType] is not a function

### ISSUE THREAD

**Issue by jcope2013** [ember-data/active-model-adapter#9]
using this plugin with ember 1.9.1 and ember data 1.13+ returns this error, i am installing it using ``` ember install active-model-adapter ```

```

Uncaught TypeError: app[initializerType] is not a function

(anonymous function) @ ember-load-initializers.js:33
default @ ember-load-initializers.js:20
(anonymous function) @ app.js:22
mod.state @ loader.js:141
tryFinally @ loader.js:21
requireModule @ loader.js:139
(anonymous function) @ app-boot.js:25

```

it is coming from https://github.com/ember-cli/ember-load-initializers/blob/master/ember-load-initializers.js

ember data 1.13+ works fine and my app fires up, is it when i install the addon the error happens

**Comment by andyryan** [comment]
Did you manage to fix this? I've just opted to use the add-on version and I'm getting this problem

**Comment by jcope2013** [comment]
@andyryan no i updated my app to 1.13 and that fixed it

**Comment by andyryan** [comment]
Awesome thanks

**Comment by fivetanley** [comment]
Closing as upgrading ember fixes it.
