### ISSUE TITLE
Is sideloading records a requirement?

### ISSUE THREAD

**Issue by jaredgalanis** [ember-data/active-model-adapter#91]
I know the documentation says that:

> This Adapter expects specific settings using ActiveModel::Serializers, embed :ids, embed_in_root: true which sideloads the records.

However, I am finding that view load times are massive in many cases where a reference is made to the parent model at the top of our relationship chain (because without making other changes, the requests for these views will load almost many many instances of models in our database).

Is the option to not sideload (or flexibility over the sideloading of) records a feature that is being considered for active-model-adapter in the future?

**Comment by jaredgalanis** [comment]
I should have also mentioned that I can see why sideloading is preferable in many cases and that it is helpful that it reduces trips to the server. That said, our use case is incorporating an Ember app into an existing Rails app and the load time occurs when users are transitioning from a Rails page to an Ember page. So while I understand that long'ish boot times can result in improved performance once inside of the app (and arguably users have come to be expect these load times when initially loading complex web apps), the waiting between pages is probably a little different and more frustrating from a user's perspective. Anyway, give everyone's time constraints I appreciate that this is probably low/not on the priority list. Thanks for all your hard work in providing ember-data and this adapter!

**Comment by fivetanley** [comment]
Sideloading isn't required, only that you send the IDs.
