### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by fivetanley** [ember-data/active-model-adapter#93]
Hey y'all,

This is an issue looking for people interested in fixing outstanding issues for ActiveModelAdapter. If you're interested in becoming a maintainer, please post below and we can start coordinating new maintainers.

Thanks.

**Comment by blimmer** [comment]
@fivetanley - @H-Bomba and I use this addon heavily would like to volunteer to help.

**Comment by fivetanley** [comment]
i invited you both as admins. thanks!

**Comment by ihoka** [comment]
Would also like to help.

**Comment by runspired** [comment]
We discussed moving this to adopted-ember-addons in our team meeting today and everyone agrees, have reached out to initiate that process.
