### ISSUE TITLE
Multiple polymorphic associations

### ISSUE THREAD

**Issue by Toshegg** [ember-data/active-model-adapter#94]
Hello! 

I'm trying to configure this module with rails api.
In rails I have this models:

- User
- Comment
- Attach

`Comment belongs_to commentable`, `Attach belongs_to attachable`, and `User has_many comments as commentable` and `has_many attaches as attachable`.

How to configure multiple polymorphic associations using your module in ember?

With this code I can set only one association, and I can't extend multiple models.
```
import Attachable from './attachable';

export default Attachable.extend({
```

Thank you for response!

**Comment by mxrguspxrt** [comment]
I can't understand your question and it seems that you have not read documentation of Ember Data hasMany and polymorphic. Please be decent enough to provide a non-working solution so others could help you to improve your solution.

**Comment by Toshegg** [comment]
@mxrguspxrt, Thank you for response!

I've already read all this links and have a solution, which I'll try to explain below.

As I sad, in rails I have 3 models:
- User
- Attachment
- Comment

It looks like this:

```ruby
class User < ActiveRecord::Base
  has_many :attachments, as: :attachable
  has_many :comments, as: :commentable
end
```
```ruby
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true
end
```
```ruby
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end
```

And I need to preload this associations in user#show request in order to speed up my website. My json response to user#show looks like that:

```json
"user": {
  "id": 1,
  "comments": [ {
    "body": "qwe",
    "commentable_id": 1,
    "commentable_type": "User"
  }],
  "attacments": [ {
    "source_url": "...",
    "attachable_id": 1,
    "attachable_type": "User"
   }]
}
```
Now, I need to setup ember models. As I read in this [discussion](http://discuss.emberjs.com/t/polymorphic-has-many-relationship/7319/10), I need to implement 2 models: Attachable and Commentable and User model should extend them, so:
```js
// models/attachble.js
import DS from 'ember-data';

export default DS.Model.extend({
  attachments: DS.hasMany('attachment')
});
```
```js
// models/commentable.js
import DS from 'ember-data';

export default DS.Model.extend({
  comments: DS.hasMany('comment')
});
```
Next, I implement my polymorphic models, as it specified in documentation to active-model-adapter:
```js
// models/attachment.js
import DS from 'ember-data';

export default DS.Model.extend({
  source: DS.attr(),
  attachable: DS.belongsTo('attachable', {polymorphic: true})
});
```
```js
// models/comment.js
import DS from 'ember-data';

export default DS.Model.extend({
  body: DS.attr(),
  comment: DS.belongsTo('commentable', {polymorphic: true})
});
```

And then I implement my User model. If I have only one polymorphic association inside user:
```js
// models/user.js
import Attachable from './attachable'

export default Attachable.extend({
});
```
it works great. But I don't know how to add second association. There are lots of examples with single association, but I can't find examples with multiple polymorphic associations in one model. Problem is that I can't extend multiple models. 
Am I missing something?
Thank you!

**Comment by mxrguspxrt** [comment]
I think your Rails models are too complicated in this scenario. I usually try to avoid polymorphic associations at any cost  (If I need them, I usually specify owner_id and owner_type manually and create 3 lines of code for finding or setting it on my own.)

You need EmbeddedRecordsMixin (http://emberjs.com/api/data/classes/DS.EmbeddedRecordsMixin.html) in you want to load them instantly - but in my experience, this does work unexpectedly (or not at all) with ActiveModelSerializer.

In my 2 years of Ember experience, I recommend to avoid complicated models (REST API exposes only 1 resource, meaning no sideloads in same request.) Speed up your page load time using JSON serialized cache in the EngineX, Apache2 or Redis. Also use ember-cli-fastboot - your initial request is rendered as pure HTML on server side on first page load.

Use lazy loading and linked resources in API, whenever possible.

**Comment by Toshegg** [comment]
@mxrguspxrt, So, if I understand you correctly, if I want more than single polymorphic associations in one model, I need to set entity_id and entity_type on my own, right?
Thank you for sharing your experience, I'm new in Ember and I'll follow your advice.

**Comment by mxrguspxrt** [comment]
No, I am saying that EmbeddedRecords and Polymorphic assocations are broken in Ember with ActiveModelSerializer, and that EmbeddedRecords suck (in REST APIs overall) and should not be used at all (because reasons listed in previous response).

Use linked resources and fastboot and saveyourself from weeks of wasted time.

**Comment by Toshegg** [comment]
@mxrguspxrt, Thank you very much!
Closing question.

**Comment by fivetanley** [comment]
Links are actually worse for a lot of cases ActiveModelSerializers in rails handles for you: sideloading. Even if your records get sideloaded, Ember Data will do an additional request. This usually ends up being worse from an end user perspective, and on mobile. I'll re-read the issue but this sounds like a bug; I don't think the correct answer is "things suck don't use them" (although I tend to agree WRT embedded record serializer), but I don't think Embedded Records are required here.

**Comment by fivetanley** [comment]
@Toshegg I think a workaround may be to use this format:

```json
"id": "1",
"attachable": {
  "id": 1,
  "type": "attachment"
}
```

For your records that have an attachable relationship.

You should be able to do this in AMS in rails:

```ruby

```ruby
class CommentSerializer < ActiveModel::Serializer
  attributes :id, :name, :body, :attachable

  def attachable
    {
      id: object.attachment.id,
     type: object.attachment.class.name.underscore
  end
end
```

**Comment by Toshegg** [comment]
@fivetanley Does this format works out of the box with active-model adapter?
As I sad, problem is that when I implement User model, i need to extend Attachable and Commentable helpers, what doesn't seem possible because of inability of multiple inheritance.

**Comment by fivetanley** [comment]
Yes, that does work, and is the preferred format. The one you are using now is also supported. I think the real problem here is maybe Ember's inheritance model's documentation not being clear.

If you want the code to be reusable between classes, you can create mixins instead.

```javascript
// app/mixins/attachable-serializer';
import DS from 'ember-data';
import Ember from 'ember';
export default Ember.Mixin.create({
  attachable: DS.belongsTo('attachable', {polymorphic: true})
});
```

```javascript
// app/mixins/commentable-serializer';
import DS from 'ember-data';
import Ember from 'ember';
export default Ember.Mixin.create({
  commentable: DS.belongsTo('attachable', {polymorphic: true})
});
```

then in your model:

```javascript
// app/models/comment
import DS from 'ember-data';
import Commentable from '../mixins/commentable-serializer';
import Attachable from '../mixins/attachable-serializer';

export default DS.extend(Commentable, Attachable, {
  // regular model attributes here
});
```

You can create as many mixins as you want, and pass them to `extend`. This is semantically different than multiple inheritance, but I think will allow you to do what you need.

**Comment by Toshegg** [comment]
@fivetanley That is exactly what I want! Thank you, I'll try to implement mixins.

**Comment by mxrguspxrt** [comment]
@fivetanley 

1. Do I understand correctly that EmbeddedMixin is not required for embedded json any more?
2. How constructing a string is slower than loading associations (because Rails uses lazy loading)?
3. What would be good approach to avoid slowness when he wants to get index of users instead of one user? (Could it be to specify on index and show different sideloads? Would it make code conditional that in one case sideload is async, in other case it is not, and all hell brokes loose?)

**Comment by fivetanley** [comment]
1) This is true for the embedded case (still required), but not the sideloaded case.
2) If you research "N+1" queries, you can see why ember data often recommends sideloading. However, it's not always a great idea to sideload if nobody is looking at the data or doing it on index (all records) endpoints. In this case it's usually better to send IDs and have a backend that can find multiple ids at once. Links don't really have this notion of caching (e.g. if you load a post with `id` of 1, it should not trigger an additional request. A Link would always do an additional request).
3) The answer is "it depends" on the use case/backend implementation.

**Comment by mxrguspxrt** [comment]
Thank you for your response.

1. So you can sideload in object root? Ok, that is cool! I always thought you need different keys for different objects. :)
2. I understand that from EmberJS perspective, cache as such using ID-s is better approach. I claim that when you will have 10000 associations, you are in a headache with this approach.

**Comment by fivetanley** [comment]
You do need different keys for different object types.

Yes, the answer is "it depends, but most people don't tend to have a large number of associations per object, and if they do, they can choose an alternate strategy".

**Comment by mxrguspxrt** [comment]
Cool! I learned something today. Thank you for this discussion. All the best. :)

**Comment by Toshegg** [comment]
@fivetanley, I tried to setup models as you sad and I've failed.
Here's my models and mixins:
```js
// mixins/attachable.js
import DS from 'ember-data';
import Ember from 'ember';

export default Ember.Mixin.create({
  attachments: DS.hasMany('attachment')
});
```
```js
// models/comment.js
import DS from 'ember-data';
import Attachable from '../mixins/attachable';

export default DS.Model.extend(Attachable, {
  body: DS.attr()
});
```
```js
// models/attachment.js
import DS from 'ember-data';

export default DS.Model.extend({
  attachable: DS.belongsTo('attachable', {polymorphic: true})
});
```
When I try to do 
```js
this.attachment.set('attachable', this.comment);
```
I get following error:
![image](https://cloud.githubusercontent.com/assets/5630034/19132157/f4a079fa-8b5a-11e6-9c4c-2ee6332990ee.png)

Also, I've found solution to set `Ember.MODEL_FACTORY_INJECTIONS` to false, but it doesn't solve the problem.

I will be very grateful to any advice how to solve this problem, can't find solution in Google.

**Comment by fivetanley** [comment]
I forgot that it needs to be a mixin, and needs to go in `app/models/attachable.js`.

**Comment by Toshegg** [comment]
@fivetanley, Thank you for quick response! Now I have
```js
// models/attachable.js
import DS from 'ember-data';
import Ember from 'ember';

export default Ember.Mixin.create({
  attachments: DS.hasMany('attachment')
});
```
And with this json response:
```json
"comment": {
  "id": 123,
  "attachments": [{
    "id": 131,
    "attachable": {
      "type": "Comment",
      "id": 123,
    }
   }]
}
```
I have following error:
![image](https://cloud.githubusercontent.com/assets/5630034/19132973/b98cbaaa-8b5e-11e6-8006-622ba3202c9f.png)
It disappears when I comment out `belongsTo('attachable', {polymorphic: true})` inside Attachment model.

Thank you!

**Comment by mxrguspxrt** [comment]
I do not know, that this format works. In your response, I think you need to use EmbeddedRecords, or you need to have:
 
{
   comment: {
       ...
       attachments: [1, 2, 3]
   },
   attachments: [...]
}

Everything is written in previous posts.

**Comment by fivetanley** [comment]
If Attachment is a model, it needs to be a DS.Model. it looks like "attachable" and "attachment" are two different things. The **mixin** should only have the relationship code and should never be instantiated from the store.

It might be easier for you to copy the relationship code in every model

```javascript
export default DS.Model.extend({
  attachable: DS.belongsTo('attachable', { polymorphic: true })
});
```

And then have an attachable mixin in `app/models/attachable`. But keep in mind Attachment and Attachable are two different things in your app so they need their own file.
