### ISSUE TITLE
Pluralization differences

### ISSUE THREAD

**Issue by stripedpumpkin** [ember-data/active-model-adapter#96]
Using active-model-adapter v2.1.1:

```js
    "active-model-adapter": {
      "version": "2.1.1",
      "from": "active-model-adapter@2.1.1",
      "resolved": "./node_shrinkwrap/active-model-adapter-2.1.1.tar",
      "dev": true
    },
```

ember 2.11:

```js
 "ember-cli": {
      "version": "2.11.1",
      "from": "ember-cli@2.11.1",
      "resolved": "./node_shrinkwrap/ember-cli-2.11.1.tar",
      "dev": true,
...
```
 and Rails 4.2.7.1, there is the following pluralization difference between

Rails:
```ruby
rails c
Loading development environment (Rails 4.2.7.1)
[1] pry(main)> 'tracking_information'.pluralize
=> "tracking_informations"
```
and Ember:
```js
'tracking_information'.pluralize()
"tracking_information"
```

Leading to the following symptom:
```ruby
# routes.rb
resources :tracking_informations, only: [:show]

# models/shipment.js
  trackingInformations: DS.hasMany('trackingInformation', { async: true }),

# hbs
      {{#each shipment.trackingInformations as |trackingInformation|}}
        trackingInformation.status
      {{/each}}
# visiting shipment page  =>
No route matches [GET] "/tracking_information/1" (ActionController::RoutingError)
```

A possible solution would be to rename the model, but is there a way to avoid renaming the model and specify the pluralization rule to use?

**Comment by blimmer** [comment]
Thanks for the report! This is actually an upstream issue with [ember-inflector](https://github.com/emberjs/ember-inflector). proof here:

https://ember-twiddle.com/5989602121998a4c31405c419a74292f?openFiles=templates.application.hbs%2C

it's actually pretty easy to make this change upstream. here's an [example](https://github.com/emberjs/ember-inflector/pull/108) of one I did a while back.

I'm going to close this and suggest you open an issue on that repo or submit a PR to fix it upstream.

**Comment by stripedpumpkin** [comment]
@blimmer I'll write the PR but could not figure out how to run the ember inflector tests.
